config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  
  namespace :admin do
    resources :users
  end 

  resource :session

  root to: 'movies#index'
end

  

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews, dependent: :destroy
  
  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
      "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    # before_action :check_if_admin

    def index
      @users = User.all.page(params[:page]).per(3)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(admin_user_params)
    if @user.save
      SystemMailer.welcome_email(@user).deliver
      redirect_to admin_users_path, notice: "you created, #{@user.firstname}!"
    else
      render :index
    end
  end

    def show

    end

    def edit
        # the code below, is meant more for a show page, how can i impliment on a index page, where the params are looped through and not passed as query string?
        @user = User.find(params[:id])
    end

    def update
      binding.pry
    @user = User.find(params[:id])
    if @user.update_attributes(admin_user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      SystemMailer.farewell_email(@user).deliver
      redirect_to admin_users_path
    end

    def login_as(x)
      @user = User.find(params[:id])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    end

    protected

  def admin_user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
#to-do system mailer not configured properly for production environment 
      # begin
      #   SystemMailer.welcome_email(@user).deliver
      #   rescue 
      # end
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :html => { :multipart => true } do |f| %>
    
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented this user from being submitted:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
        <%= f.label "email" %><br>
        <%= f.text_field "email" %>
    </div>

    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>

    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>

    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>

    <div>
      <%= f.label "password_confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div>
      <%= f.label "admin", "User is admin: "  %>
      <%= f.check_box "admin" %>
    </div>
    <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/_user.html.erb
    <p>(<%= link_to "edit", edit_admin_user_path(user) %>, <%= link_to "delete", admin_user_path(user), method: :delete, data: { confirm: "You sure?" } %>, <%= link_to "login as", session_path(user) %>)</p>
  <h3>Name: <%= user.full_name %> </h3> 


  <h4>Email: <%= user.email %></h4>

    <hr>

app/views/admin/users/edit.html.erb
<%= link_to "Back to admin page", admin_users_path(@user) %>
<!-- what shoud the path be above??? -->
<h2>Edit this user.</h2>
    <%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin Page</h1>
<div>
  <%= link_to "Create a user!", new_admin_user_path%>
</div>
<div>
  <%= link_to "Back to movie list!", movies_path %>
</div>
<h2>here is a list of all users </h2>
<div>
  
  <%= paginate @users  %>

  <%= render @users %>
</div>

   

app/views/admin/users/new.html.erb
<%= link_to "Back to all users", admin_users_path %>
    <h2>Create a new user</h2>
    <%= render 'form' %>

app/views/admin/users/show.html.erb
show.html.erb