config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  
  namespace :admin do
    resources :users
  end 

  resource :session

  root to: 'movies#index'
end

  

app/views/layouts/_footer.html.erb
 <footer>

</footer>

app/views/layouts/_header.html.erb
<div id='top-area'>    

  <h1 id="rotten-title">Rotten Mangoes</h1>
  <small id="session-links">
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("bla"), method: :delete %>)
        <% if current_user.admin %>
        you're an admin
     <%= link_to "Admin", admin_users_path %> 
         <%end%>
          <% if session[:acting_as] %>
     <%= link_to "Back to admin-mode", session_path("bla"), method: :delete %> 
         <%end%>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
  <div id='icon-holder'>
    <img id="search-icon" src="searchy.png">
  </div>

  <%= form_tag(movies_path, :id => 'simple-search-form', :class => 'container hidden', method: "get") do %>
      <%params[:title] = 'search' if !params[:title] || !params[:title] == ''   %>

    <%= text_field_tag :title, params[:title] %>
      
    <%= submit_tag "Search", { name: nil } %>
  <% end %>
    
    <span id="submit-a-movie"><%= link_to "Submit a movie!",  new_movie_path %> </span>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
    <html>
    <head>
      <title>RottenMangoes</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>

      
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
        <% end %>
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </body>
    </html>